//! The embedded wasmtime host for plugin components.
//!
//! [`PluginHost`] instantiates a plugin component against the `ulb-plugin`
//! world from [`ulb_plugin_sdk::WIT`] and drives its `manifest`, `run`,
//! and `configure` entries. Host bindings are generated by wasmtime's
literal://! `bindgen!` macro from the exact WIT text in the sdk crate, so the host
literal://! and a plugin cannot drift apart.
//!
//! During [`PluginHost::configure`] the host implements the world's
//! `task-registrar` import (ARCHITECTURE.md §3.2): the plugin calls
//! `register-task` for each task it wants the build to run, and the host
//! accumulates them into the module's task graph. The import is bound in
//! the linker for every instantiation so a component built against an
//! older ABI that never imports `task-registrar` still instantiates; the
//! registrar itself is only reachable inside a `configure` call.

use std::collections::HashSet;
use std::path::{Path, PathBuf};

use wasmtime::component::{Component, Linker, ResourceTable};
use wasmtime::{Config, Engine, Store};
use wasmtime_wasi::{WasiCtx, WasiCtxBuilder, WasiCtxView, WasiView, p2};

use crate::task::{AllowlistedTool, Task as BuildTask, TaskAction, TaskGraph};

/// Generated host bindings for the `ulb-plugin` world.
///
/// The bindings come from the `plugin.wit` in the sdk crate, resolved
literal:/// relative to this crate's manifest dir, so the host and a
/// plugin cannot drift apart. The `unsafe` in this module is confined to
/// the code wasmtime's `bindgen!` macro emits; nothing else in this crate
/// uses `unsafe`.
mod bindings {
    #![allow(unsafe_code)]
    wasmtime::component::bindgen!({
        path: "../ulb-plugin-sdk/plugin.wit",
        world: "plugin",
    });
}

/// Host bindings for the pre-`configure` `ulb-plugin` world
/// (`legacy-plugin.wit` in the sdk crate). The full world requires the
/// `configure` export, which a component built against the older ABI does
/// not have, so [`PluginHost::run`] and `manifest_of_bytes` instantiate
/// against this world instead: a legacy-world instantiation only asks for
/// `manifest` and `run`, and a newer component that exports both still
/// satisfies it (its extra `configure` export is ignored).
mod legacy_bindings {
    #![allow(unsafe_code)]
    wasmtime::component::bindgen!({
        path: "../ulb-plugin-sdk/legacy-plugin.wit",
        world: "plugin",
    });
}

/// A loaded plugin component bound to the full (current) world, used by
/// [`PluginHost::configure`].
struct LoadedPlugin {
    plugin: bindings::Plugin,
    store: Store<HostCtx>,
}

/// A loaded plugin component bound to the legacy (pre-`configure`) world,
/// used by [`PluginHost::run`] and `manifest_of_bytes`.
struct LoadedLegacyPlugin {
    plugin: legacy_bindings::Plugin,
    store: Store<HostCtx>,
}

/// The per-store state: a WASI context plus the resource table it needs,
/// and the task registrar a plugin writes into during `configure`.
///
/// The wasip2 std runtime imports `wasi:io/poll` and friends even in a
/// pure-compute plugin, so the host exposes a WASI view (ARCHITECTURE.md
/// §3.3). The plugin ABI itself defines no resources yet; the table stays
/// empty until the ABI grows a resource-bearing entry point.
struct HostCtx {
    wasi: WasiCtx,
    table: ResourceTable,
    /// The task registrar bound to the current `configure` session.
    /// `None` outside configuration: a task is meaningless without the
    /// module that owns it, so a `register-task` call that is not part of
    /// a `configure` session is refused.
    registrar: Option<RegistrarState>,
}

/// The host side of a `configure` session: the graph being built, the
/// module it belongs to, and the tools the plugin's manifest declared for
/// its `run-tool` actions (§3.5).
struct RegistrarState {
    graph: TaskGraph,
    module: String,
    declared_tools: HashSet<AllowlistedTool>,
}

impl RegistrarState {
    /// Registers a task a plugin reported through the WIT `task` record.
    ///
    /// A `run-tool` action whose tool the plugin's manifest did not
    /// declare is refused here, in-band, so the plugin can surface it in
    /// its own `configure` result (§3.5: a plugin cannot silently start
    /// invoking something new after being installed).
    fn register(&mut self, task: bindings::ulite::ulb::task_registrar::Task) -> Result<(), String> {
        if let bindings::ulite::ulb::task_registrar::Action::RunTool(args) = &task.action {
            let tool = AllowlistedTool::from(args.tool);
            if !self.declared_tools.contains(&tool) {
                return Err(format!(
                    "tool '{}' is not declared in the plugin manifest",
                    tool.as_str()
                ));
            }
        }
        let task = BuildTask {
            name: task.name,
            module: self.module.clone(),
            inputs: task.inputs.into_iter().map(PathBuf::from).collect(),
            outputs: task.outputs.into_iter().map(PathBuf::from).collect(),
            depends_on: task.depends_on,
            action: task.action.into(),
        };
        self.graph.register(task)
    }
}

/// The registrar host trait (ARCHITECTURE.md §3.2): a plugin calls
/// `register-task` during `configure`; the host accepts or refuses each
/// task and reports failures back to the plugin in-band, so a plugin can
/// decide whether to surface them in its own `configure` result.
impl bindings::ulite::ulb::task_registrar::Host for HostCtx {
    fn register_task(
        &mut self,
        task: bindings::ulite::ulb::task_registrar::Task,
    ) -> Result<(), String> {
        let Some(registrar) = &mut self.registrar else {
            return Err("register-task called outside configure".to_owned());
        };
        registrar.register(task)
    }
}

impl From<bindings::ulite::ulb::task_registrar::Action> for TaskAction {
    fn from(action: bindings::ulite::ulb::task_registrar::Action) -> Self {
        use bindings::ulite::ulb::task_registrar::Action as W;
        match action {
            W::CopyFile(args) => TaskAction::Copy {
                from: PathBuf::from(args.source),
                to: PathBuf::from(args.destination),
            },
            W::RunTool(args) => TaskAction::RunTool {
                tool: args.tool.into(),
                args: args.args,
                cwd: PathBuf::from(args.cwd),
            },
            W::WriteFile(args) => TaskAction::WriteFile {
                to: PathBuf::from(args.path),
                contents: args.contents,
            },
        }
    }
}

impl From<bindings::ulite::ulb::task_registrar::AllowlistedTool> for crate::task::AllowlistedTool {
    fn from(tool: bindings::ulite::ulb::task_registrar::AllowlistedTool) -> Self {
        use bindings::ulite::ulb::task_registrar::AllowlistedTool as W;
        match tool {
            W::Cp => Self::Copy,
            W::Cat => Self::Cat,
            W::Mkdir => Self::Mkdir,
            W::Echo => Self::Echo,
            W::Javac => Self::Javac,
            W::Kotlinc => Self::Kotlinc,
            W::Jar => Self::Jar,
            W::Java => Self::Java,
        }
    }
}

impl WasiView for HostCtx {
    fn ctx(&mut self) -> WasiCtxView<'_> {
        WasiCtxView {
            ctx: &mut self.wasi,
            table: &mut self.table,
        }
    }
}

/// Errors that can occur while loading or running a plugin.
#[derive(Debug)]
pub enum HostError {
    /// The plugin could not be compiled or instantiated (bad component,
    /// wrong world, incompatible ABI).
    Load(String),
    /// A call into a loaded plugin failed (trap, or a `manifest`/`run`
    /// ABI mismatch surfaced at call time).
    Call(String),
}

impl std::fmt::Display for HostError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::Load(message) => write!(f, "plugin load failed: {message}"),
            Self::Call(message) => write!(f, "plugin call failed: {message}"),
        }
    }
}

impl std::error::Error for HostError {}

/// The embedded wasmtime engine that plugin components run in.
pub struct PluginHost {
    engine: Engine,
}

/// The identity a plugin reports in its `manifest` entry.
pub struct PluginManifest {
    /// Plugin identifier, e.g. `ulite/android`.
    pub name: String,
    /// Plugin version, e.g. `1.4.0`.
    pub version: String,
    /// Plugin-ABI version the plugin was built against.
    pub abi_version: String,
    /// The allowlisted tools the plugin's task actions invoke
    /// (ARCHITECTURE.md §3.5); the registrar refuses a `run-tool` action
    /// whose tool is not declared here.
    pub tools: Vec<String>,
}

impl PluginHost {
    /// A host engine with the component model enabled.
    pub fn new() -> Result<Self, HostError> {
        let mut config = Config::new();
        config.wasm_component_model(true);
        let engine = Engine::new(&config).map_err(|error| HostError::Load(error.to_string()))?;
        Ok(Self { engine })
    }

    /// Loads the component in `path` and runs its `run` entry point with
    /// `input`.
    ///
    /// Before calling `run`, the plugin's `manifest` is read and checked
    /// against [`ulb_plugin_sdk::ABI_VERSION`]; an out-of-range
    /// `abi-version` is rejected without executing plugin code
    /// (ARCHITECTURE.md §3.7).
    ///
    /// # Errors
    ///
    /// Returns [`HostError::Load`] for any failure reading or
    /// instantiating the component, and [`HostError::Call`] if a plugin
    /// entry point traps or the ABI check fails.
    pub fn run(&self, path: &Path, input: &str) -> Result<String, HostError> {
        let mut plugin = self.load_legacy(path)?;
        let manifest = plugin
            .manifest()
            .map_err(|error| HostError::Call(error.to_string()))?;
        self.check_abi(&manifest)?;
        plugin
            .run(input)
            .map_err(|error| HostError::Call(error.to_string()))
    }

    /// Loads the component in `path`, runs its `configure` entry point
    /// against `config_json`, and returns the task graph the plugin
    /// registered (ARCHITECTURE.md §9 step 7).
    ///
    /// Before calling `configure`, the plugin's `manifest` is read and
    /// checked against [`ulb_plugin_sdk::ABI_VERSION`]; an out-of-range
    /// `abi-version` is rejected without executing plugin code
    /// (ARCHITECTURE.md §3.7). Each task the plugin registers through
    /// `register-task` is validated as it arrives (duplicate name, tool
    /// outside the allowlist, tool not declared in the plugin's manifest
    /// per §3.5), and the assembled graph is validated once more for
    /// undefined dependencies and cycles before it is returned.
    ///
    /// # Errors
    ///
    /// Returns [`HostError::Load`] for any failure reading or
    /// instantiating the component, [`HostError::Call`] if a plugin entry
    /// point traps, the ABI check fails, the plugin rejects the
    /// configuration, or the registered graph cannot be scheduled.
    ///
    /// # Examples
    ///
    /// Configuring requires a real component, so the example builds the
    /// workspace's `ulb-plugin-fixture` for `wasm32-wasip2` and drives the
    /// graph it registers through the executor:
    ///
    /// ```rust
    /// use std::path::PathBuf;
    /// use std::process::Command;
    ///
    /// use uliab::host::PluginHost;
    /// use uliab::task::{Executor, FingerprintContext, FingerprintStore};
    ///
    /// let workspace = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
    ///     .parent().unwrap().parent().unwrap().to_path_buf();
    /// let built = Command::new("cargo")
    ///     .args(["build", "-p", "ulb-plugin-fixture", "--target", "wasm32-wasip2"])
    ///     .current_dir(&workspace)
    ///     .status().expect("build the fixture plugin");
    /// assert!(built.success());
    /// let target = std::env::var_os("CARGO_TARGET_DIR")
    ///     .map(PathBuf::from)
    ///     .unwrap_or_else(|| workspace.join("target"));
    /// let fixture = target.join("wasm32-wasip2/debug/ulb_plugin_fixture.wasm");
    ///
    /// let workdir = std::env::temp_dir().join(format!(
    ///     "uliab-configure-doc-{}", std::process::id()
    /// ));
    /// std::fs::create_dir_all(&workdir).unwrap();
    /// std::fs::write(workdir.join("in.txt"), "hello").unwrap();
    /// let config = format!(
    ///     r#"{{"source": {:?}, "output": {:?}}}"#,
    ///     workdir.join("in.txt").display().to_string(),
    ///     workdir.join("out.txt").display().to_string(),
    /// );
    ///
    /// let host = PluginHost::new().expect("engine");
    /// let graph = host
    ///     .configure(&fixture, "app", &config)
    ///     .expect("plugin configures");
    /// let ctx = FingerprintContext {
    ///     plugin_version: "0.1.0".to_owned(),
    ///     config_hash: "doc".to_owned(),
    /// };
    /// let mut store = FingerprintStore::load(workdir.join("state.json")).unwrap();
    /// let result = Executor::new([uliab::task::AllowlistedTool::Echo])
    ///     .execute(&graph, &ctx, &mut store)
    ///     .expect("schedules");
    /// assert_eq!(result.ran, 2);
    /// assert_eq!(std::fs::read(workdir.join("out.txt")).unwrap(), b"hello");
    /// ```
    pub fn configure(
        &self,
        path: &Path,
        module: &str,
        config_json: &str,
    ) -> Result<TaskGraph, HostError> {
        let mut plugin = self.load_full(path)?;
        let manifest = plugin
            .manifest()
            .map_err(|error| HostError::Call(error.to_string()))?;
        self.check_abi(&manifest)?;
        let declared_tools = parse_declared_tools(&manifest)?;
        plugin.store.data_mut().registrar = Some(RegistrarState {
            graph: TaskGraph::new(),
            module: module.to_owned(),
            declared_tools,
        });
        let outcome = plugin
            .plugin
            .ulite_ulb_ulb_plugin()
            .call_configure(&mut plugin.store, config_json)
            .map_err(|error| HostError::Call(error.to_string()))?;
        if let Err(message) = outcome {
            return Err(HostError::Call(format!(
                "plugin '{}' rejected the configuration: {message}",
                manifest.name
            )));
        }
        let state = plugin.store.data_mut().registrar.take().ok_or_else(|| {
            HostError::Call("plugin configured without a task registrar".to_owned())
        })?;
        // Validate the graph as a whole — the per-task checks during
        // registration cannot catch a dependency on a task that is never
        // registered, or a cycle.
        state.graph.waves().map_err(|error| {
            HostError::Call(format!(
                "plugin '{}' registered an invalid task graph: {error}",
                manifest.name
            ))
        })?;
        Ok(state.graph)
    }

    /// Reads and instantiates the component in `path` against the full
    /// (current) world.
    fn load_full(&self, path: &Path) -> Result<LoadedPlugin, HostError> {
        let component = Component::from_file(&self.engine, path)
            .map_err(|error| HostError::Load(error.to_string()))?;
        self.instantiate_full(component)
    }

    /// Reads and instantiates the component in `path` against the legacy
    /// (pre-`configure`) world.
    fn load_legacy(&self, path: &Path) -> Result<LoadedLegacyPlugin, HostError> {
        let component = Component::from_file(&self.engine, path)
            .map_err(|error| HostError::Load(error.to_string()))?;
        self.instantiate_legacy(component)
    }

    /// The shared linker and store for one instantiation: a WASI view for
    /// the wasip2 std runtime plus the task-registrar import, bound for
    /// every component even though only the full world references it.
    fn store_and_linker(&self) -> Result<(Linker<HostCtx>, Store<HostCtx>), HostError> {
        let mut linker = Linker::new(&self.engine);
        // The wasip2 std runtime imports wasi:io/poll (and friends) even in
        // a pure-compute plugin, so the linker carries a WASI view.
        p2::add_to_linker_sync::<HostCtx>(&mut linker)
            .map_err(|error| HostError::Load(error.to_string()))?;
        // The task-registrar import is bound for every instantiation. A
        // component built against the 0.1 ABI without that import simply
        // never references it, so it still instantiates; the host impl
        // refuses register-task calls made outside a configure session.
        bindings::Plugin::add_to_linker::<HostCtx, wasmtime::component::HasSelf<HostCtx>>(
            &mut linker,
            |host| host,
        )
        .map_err(|error| HostError::Load(error.to_string()))?;
        let store = Store::new(
            &self.engine,
            HostCtx {
                wasi: WasiCtxBuilder::new()
                    .inherit_stdout()
                    .inherit_stderr()
                    .build(),
                table: ResourceTable::new(),
                registrar: None,
            },
        );
        Ok((linker, store))
    }

    /// Instantiates an already-loaded component into a store with a WASI
    /// view and the full plugin ABI rooted in the linker.
    fn instantiate_full(&self, component: Component) -> Result<LoadedPlugin, HostError> {
        let (linker, mut store) = self.store_and_linker()?;
        let plugin = bindings::Plugin::instantiate(&mut store, &component, &linker)
            .map_err(|error| HostError::Load(error.to_string()))?;
        Ok(LoadedPlugin { plugin, store })
    }

    /// Instantiates an already-loaded component against the legacy world.
    fn instantiate_legacy(&self, component: Component) -> Result<LoadedLegacyPlugin, HostError> {
        let (linker, mut store) = self.store_and_linker()?;
        let plugin = legacy_bindings::Plugin::instantiate(&mut store, &component, &linker)
            .map_err(|error| HostError::Load(error.to_string()))?;
        Ok(LoadedLegacyPlugin { plugin, store })
    }

    /// Reads a plugin's `manifest` entry from a component held in memory.
    ///
    /// Used by the registry client to verify a downloaded artifact before
    /// it is written to the cache ([`crate::registry::Registry`]). The
    /// component is instantiated but never run.
    ///
    /// # Errors
    ///
    /// Returns [`HostError::Load`] when the bytes are not a valid
    /// `ulb-plugin` component and [`HostError::Call`] when the `manifest`
    /// entry point fails.
    pub fn manifest_of_bytes(&self, wasm: &[u8]) -> Result<PluginManifest, HostError> {
        let component = Component::from_binary(&self.engine, wasm)
            .map_err(|error| HostError::Load(error.to_string()))?;
        let mut plugin = self.instantiate_legacy(component)?;
        plugin.manifest()
    }

    /// Verifies the plugin's reported ABI version against the host's.
    ///
    /// The 0.1 rule is an exact match on `abi-version`; a later major
    /// version widens this to a compatible-range check per ARCHITECTURE.md
    /// §3.6.
    fn check_abi(&self, manifest: &PluginManifest) -> Result<(), HostError> {
        if manifest.abi_version == ulb_plugin_sdk::ABI_VERSION {
            Ok(())
        } else {
            Err(HostError::Call(format!(
                "plugin abi-version '{}' does not match host abi-version '{}'",
                manifest.abi_version,
                ulb_plugin_sdk::ABI_VERSION
            )))
        }
    }
}

/// Parses the tools a plugin's manifest declares for its `run-tool`
/// actions into the closed [`AllowlistedTool`] set, refusing a name the
/// host does not allowlist (§3.5).
fn parse_declared_tools(manifest: &PluginManifest) -> Result<HashSet<AllowlistedTool>, HostError> {
    let mut tools = HashSet::new();
    for name in &manifest.tools {
        let tool = AllowlistedTool::parse(name).ok_or_else(|| {
            HostError::Call(format!(
                "plugin '{}' declares tool '{name}', which is not on the host allowlist",
                manifest.name
            ))
        })?;
        tools.insert(tool);
    }
    Ok(tools)
}

impl LoadedPlugin {
    /// Calls the plugin's `manifest` entry point.
    fn manifest(&mut self) -> Result<PluginManifest, HostError> {
        let manifest = self
            .plugin
            .ulite_ulb_ulb_plugin()
            .call_manifest(&mut self.store)
            .map_err(|error| HostError::Call(error.to_string()))?;
        Ok(PluginManifest {
            name: manifest.name,
            version: manifest.version,
            abi_version: manifest.abi_version,
            tools: manifest.tools,
        })
    }
}

impl LoadedLegacyPlugin {
    /// Calls the plugin's `manifest` entry point.
    fn manifest(&mut self) -> Result<PluginManifest, HostError> {
        let manifest = self
            .plugin
            .ulite_ulb_ulb_plugin()
            .call_manifest(&mut self.store)
            .map_err(|error| HostError::Call(error.to_string()))?;
        Ok(PluginManifest {
            name: manifest.name,
            version: manifest.version,
            abi_version: manifest.abi_version,
            tools: manifest.tools,
        })
    }

    /// Calls the plugin's `run` entry point.
    fn run(&mut self, input: &str) -> Result<String, HostError> {
        self.plugin
            .ulite_ulb_ulb_plugin()
            .call_run(&mut self.store, input)
            .map_err(|error| HostError::Call(error.to_string()))
    }
}
