//! The embedded wasmtime host for plugin components.
//!
//! [`PluginHost`] instantiates a plugin component against the `ulb-plugin`
//! world from [`ulb_plugin_sdk::WIT`] and drives its `manifest`/`run`
//! entries. Host bindings are generated by wasmtime's `bindgen!` macro
literal://! from the exact WIT text in the sdk crate, so the host
//! and a plugin cannot drift apart.

use std::path::Path;

use wasmtime::component::{Component, Linker, ResourceTable};
use wasmtime::{Config, Engine, Store};
use wasmtime_wasi::{WasiCtx, WasiCtxBuilder, WasiCtxView, WasiView, p2};

/// Generated host bindings for the `ulb-plugin` world.
///
/// The bindings come from the `plugin.wit` in the sdk crate, resolved
literal:/// relative to this crate's manifest dir, so the host and a
/// plugin cannot drift apart. The `unsafe` in this module is confined to
/// the code wasmtime's `bindgen!` macro emits; nothing else in this crate
/// uses `unsafe`.
mod bindings {
    #![allow(unsafe_code)]
    wasmtime::component::bindgen!({
        path: "../ulb-plugin-sdk/plugin.wit",
        world: "plugin",
    });
}

/// A loaded plugin component, bound to the store it was instantiated in.
struct LoadedPlugin {
    plugin: bindings::Plugin,
    store: Store<HostCtx>,
}

/// The per-store state: a WASI context plus the resource table it needs.
///
/// The wasip2 std runtime imports `wasi:io/poll` and friends even in a
/// pure-compute plugin, so the host exposes a WASI view (ARCHITECTURE.md
/// §3.3). The plugin ABI itself defines no resources yet; the table stays
/// empty until the ABI grows a resource-bearing entry point.
struct HostCtx {
    wasi: WasiCtx,
    table: ResourceTable,
}

impl WasiView for HostCtx {
    fn ctx(&mut self) -> WasiCtxView<'_> {
        WasiCtxView {
            ctx: &mut self.wasi,
            table: &mut self.table,
        }
    }
}

/// Errors that can occur while loading or running a plugin.
#[derive(Debug)]
pub enum HostError {
    /// The plugin could not be compiled or instantiated (bad component,
    /// wrong world, incompatible ABI).
    Load(String),
    /// A call into a loaded plugin failed (trap, or a `manifest`/`run`
    /// ABI mismatch surfaced at call time).
    Call(String),
}

impl std::fmt::Display for HostError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::Load(message) => write!(f, "plugin load failed: {message}"),
            Self::Call(message) => write!(f, "plugin call failed: {message}"),
        }
    }
}

impl std::error::Error for HostError {}

/// The embedded wasmtime engine that plugin components run in.
pub struct PluginHost {
    engine: Engine,
}

/// The identity a plugin reports in its `manifest` entry.
pub struct PluginManifest {
    /// Plugin identifier, e.g. `ulite/android`.
    pub name: String,
    /// Plugin version, e.g. `1.4.0`.
    pub version: String,
    /// Plugin-ABI version the plugin was built against.
    pub abi_version: String,
}

impl PluginHost {
    /// A host engine with the component model enabled.
    pub fn new() -> Result<Self, HostError> {
        let mut config = Config::new();
        config.wasm_component_model(true);
        let engine = Engine::new(&config).map_err(|error| HostError::Load(error.to_string()))?;
        Ok(Self { engine })
    }

    /// Loads the component in `path` and runs its `run` entry point with
    /// `input`.
    ///
    /// Before calling `run`, the plugin's `manifest` is read and checked
    /// against [`ulb_plugin_sdk::ABI_VERSION`]; an out-of-range
    /// `abi-version` is rejected without executing plugin code
    /// (ARCHITECTURE.md §3.7).
    ///
    /// # Errors
    ///
    /// Returns [`HostError::Load`] for any failure reading or
    /// instantiating the component, and [`HostError::Call`] if a plugin
    /// entry point traps or the ABI check fails.
    pub fn run(&self, path: &Path, input: &str) -> Result<String, HostError> {
        let mut plugin = self.load(path)?;
        let manifest = plugin
            .manifest()
            .map_err(|error| HostError::Call(error.to_string()))?;
        self.check_abi(&manifest)?;
        plugin
            .run(input)
            .map_err(|error| HostError::Call(error.to_string()))
    }

    /// Reads and instantiates the component in `path`.
    fn load(&self, path: &Path) -> Result<LoadedPlugin, HostError> {
        let component = Component::from_file(&self.engine, path)
            .map_err(|error| HostError::Load(error.to_string()))?;
        let mut linker = Linker::new(&self.engine);
        // The wasip2 std runtime imports wasi:io/poll (and friends) even in
        // a pure-compute plugin, so the linker carries a WASI view. The
        // 0.1 ABI itself defines no resources; plugin-facing imports will
        // be rooted here once the ABI grows.
        p2::add_to_linker_sync::<HostCtx>(&mut linker)
            .map_err(|error| HostError::Load(error.to_string()))?;
        let mut store = Store::new(
            &self.engine,
            HostCtx {
                wasi: WasiCtxBuilder::new()
                    .inherit_stdout()
                    .inherit_stderr()
                    .build(),
                table: ResourceTable::new(),
            },
        );
        let plugin = bindings::Plugin::instantiate(&mut store, &component, &linker)
            .map_err(|error| HostError::Load(error.to_string()))?;
        Ok(LoadedPlugin { plugin, store })
    }

    /// Verifies the plugin's reported ABI version against the host's.
    ///
    /// The 0.1 rule is an exact match on `abi-version`; a later major
    /// version widens this to a compatible-range check per ARCHITECTURE.md
    /// §3.6.
    fn check_abi(&self, manifest: &PluginManifest) -> Result<(), HostError> {
        if manifest.abi_version == ulb_plugin_sdk::ABI_VERSION {
            Ok(())
        } else {
            Err(HostError::Call(format!(
                "plugin abi-version '{}' does not match host abi-version '{}'",
                manifest.abi_version,
                ulb_plugin_sdk::ABI_VERSION
            )))
        }
    }
}

impl LoadedPlugin {
    /// Calls the plugin's `manifest` entry point.
    fn manifest(&mut self) -> Result<PluginManifest, HostError> {
        let manifest = self
            .plugin
            .ulite_ulb_ulb_plugin()
            .call_manifest(&mut self.store)
            .map_err(|error| HostError::Call(error.to_string()))?;
        Ok(PluginManifest {
            name: manifest.name,
            version: manifest.version,
            abi_version: manifest.abi_version,
        })
    }

    /// Calls the plugin's `run` entry point.
    fn run(&mut self, input: &str) -> Result<String, HostError> {
        self.plugin
            .ulite_ulb_ulb_plugin()
            .call_run(&mut self.store, input)
            .map_err(|error| HostError::Call(error.to_string()))
    }
}
